'''Output data validation module'''
from typing import List
from pydantic import BaseModel  # pylint: disable=no-name-in-module


class BaseOutput(BaseModel):  # pylint: disable=too-few-public-methods
    '''Type of output data.

    Attributes:
        generated_texts: list of texts generated by the model'''
    generated_texts: List[str]
